name: Build, test and publish jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start db image for unit and integration tests
        run: docker-compose up -d -V db
        working-directory: ./testdb
      - name: Wait until db is up
        run: docker-compose up -V --exit-code-from await-db await-db
        working-directory: ./testdb

      - name: Build unit-tested jar with gradle
        run: ./gradlew stage
      - name: Print version info
        run: ./print_version.sh
        working-directory: ./inttest

      - name: Test with missing parameters
        run: ./missing_params.sh
        working-directory: ./inttest
      - name: Test with good configuration
        run: ./exit_ok.sh
        working-directory: ./inttest
      - name: Test with env variables
        run: ./env_ok.sh
        working-directory: ./inttest
      - name: Test with bad configuration
        run: ./exit_err.sh
        working-directory: ./inttest
      - name: Test with biig resultset
        run: ./fatty_ok.sh
        working-directory: ./inttest
      - name: Test with biig json containing no sql tags at all
        run: ./json_no_sql_tags_ok.sh
        working-directory: ./inttest
      - name: Test with passing validation against json schema
        run: ./validation_ok.sh
        working-directory: ./inttest
      - name: Test with failing validation against json schema
        run: ./validation_err.sh
        working-directory: ./inttest

      - name: Upload verified jar to bintray
        run: ./gradlew bintrayUpload -Psql2json.publish.user=${{ secrets.BINTRAY_USER }} -Psql2json.publish.pass=${{ secrets.BINTRAY_PASS }}