version: '3'

services:
  db:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  await-db:
    image: postgis/postgis:11-2.5-alpine
    command: /var/lib/postgresql/data/await-db/await.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "./await-db:/var/lib/postgresql/data/await-db"